[package]
name = "logline-lab-ruler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
logline-act.workspace = true
logline-lab-core.workspace = true
logline-lab-spine.workspace = true
logline-lab-clock.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
logline-lab-local.workspace = true

[lints]
workspace = true
