//! Recovery scanner.
//!
//! Source fruits are raw material, not authority (Operator §6). This scanner
//! catches two classes of poison before material is promoted:
//!
//! - **false authority** — text that claims a file, an LLM, or an assistant is
//!   the source of semantic truth (A29).
//! - **storage-as-truth** — text that frames files or SQLite as the spine / the
//!   official semantic storage / the ledger of truth (A30).
//!
//! It reports findings; it never silently "fixes" material.

#![forbid(unsafe_code)]

use serde::{Deserialize, Serialize};

/// The category of a finding.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Category {
    FalseAuthority,
    StorageTruth,
}

/// One scan finding.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Finding {
    pub category: Category,
    pub line: usize,
    pub pattern: String,
    pub excerpt: String,
}

const FALSE_AUTHORITY: &[&str] = &[
    "source of truth",
    "single source of truth",
    "this file is authoritative",
    "authoritative source",
    "llm-generated authority",
    "ai-generated authority",
    "the assistant decided",
    "assistant-generated authority",
    "the model is the authority",
    "generated by the llm and is canonical",
];

const STORAGE_TRUTH: &[&str] = &[
    "sqlite is the truth",
    "sqlite as truth",
    "sqlite as the spine",
    "sqlite is the spine",
    "sqlite as ledger",
    "sqlite is the ledger",
    "file is the source of truth",
    "files are the source of truth",
    "files are the official semantic storage",
    "the database is the truth",
    "database is the spine of truth",
    "the ledger is the database",
];

fn scan_with(text: &str, patterns: &[&str], category: Category) -> Vec<Finding> {
    let mut findings = Vec::new();
    for (i, raw) in text.lines().enumerate() {
        let lower = raw.to_lowercase();
        for pat in patterns {
            if lower.contains(pat) {
                findings.push(Finding {
                    category,
                    line: i + 1,
                    pattern: (*pat).to_string(),
                    excerpt: raw.trim().to_string(),
                });
            }
        }
    }
    findings
}

/// Scan for false-authority language (A29).
pub fn scan_authority(text: &str) -> Vec<Finding> {
    scan_with(text, FALSE_AUTHORITY, Category::FalseAuthority)
}

/// Scan for file/SQLite-as-truth language (A30).
pub fn scan_storage(text: &str) -> Vec<Finding> {
    scan_with(text, STORAGE_TRUTH, Category::StorageTruth)
}

/// Scan text for all categories.
pub fn scan_text(text: &str) -> Vec<Finding> {
    let mut all = scan_authority(text);
    all.extend(scan_storage(text));
    all
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A29 — Recovery scan catches false authority.
    #[test]
    fn a29_catches_false_authority() {
        let poisoned = "Intro line.\nThis file is the single source of truth for the lab.\nThe assistant decided the final architecture.";
        let findings = scan_authority(poisoned);
        assert!(findings.iter().any(|f| f.category == Category::FalseAuthority));
        assert!(findings.len() >= 2);

        // Clean text yields nothing.
        let clean = "Source fruits are raw material, not authority. The Act is the record.";
        assert!(scan_authority(clean).is_empty());
    }

    /// A30 — Storage scan rejects file/SQLite truth language.
    #[test]
    fn a30_rejects_storage_truth_language() {
        let poisoned = "The local store uses SQLite.\nSQLite is the truth and the spine of the system.\nFiles are the official semantic storage.";
        let findings = scan_storage(poisoned);
        assert!(findings.iter().any(|f| f.category == Category::StorageTruth));
        assert!(findings.len() >= 2);

        // Describing SQLite/files as a *cache* is fine.
        let clean = "The local outbox is a provisional cache, never truth. SQLite would only be a cache.";
        assert!(scan_storage(clean).is_empty());
    }
}
